package project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.persistence.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class AdminPage extends BaseFrame {

    public static DefaultTableModel customerTable = new DefaultTableModel();
    public static DefaultTableModel repTable = new DefaultTableModel();
    public static DefaultTableModel complaintTable = new DefaultTableModel();
    List<User> listUserTable = new ArrayList<>();
    List<Complaint> listComplaintTable = new ArrayList();

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        super();
        initComponents();

        lblUserName.setText(((Admin) UserManager.getUser()).getFirstName() + " " + ((Admin) UserManager.getUser()).getLastName());
        btnViewComplaintLogs.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new LogViewer("Complaint Logs", "complaint_logs.log").setVisible(true);
                AdminPage.this.setVisible(false);
            }
        });

        btnViewUserLogs.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new LogViewer("User Activity Logs", "user_logs.txt").setVisible(true);
                AdminPage.this.setVisible(false);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowCus = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        btnShowRep = new javax.swing.JButton();
        btnCreateRep = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnChngActivity = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnShowComp = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnBrand = new javax.swing.JButton();
        btnViewComplaintLogs = new javax.swing.JButton();
        btnViewUserLogs = new javax.swing.JButton();

        btnShowCus.setText("Show Customers");
        btnShowCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCusActionPerformed(evt);
            }
        });

        lblUserName.setText("Sümeyye Kırmızı");

        btnShowRep.setText("Show Customer Representatives");
        btnShowRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRepActionPerformed(evt);
            }
        });

        btnCreateRep.setText("Create Representative Account");
        btnCreateRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRepActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnChngActivity.setText("Change Activity of User");
        btnChngActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChngActivityActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        btnShowComp.setText("Show Complaints");
        btnShowComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCompActionPerformed(evt);
            }
        });

        btnDetails.setText("Complaint Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnBrand.setText("Save or Edit Brand");
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        btnViewComplaintLogs.setText("View Complaint Logs");

        btnViewUserLogs.setText("View User Logs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewUserLogs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewComplaintLogs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreateRep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnShowComp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowCus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnShowRep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChngActivity))
                            .addComponent(btnBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(btnExit)
                    .addComponent(btnEdit)
                    .addComponent(btnViewComplaintLogs)
                    .addComponent(btnViewUserLogs))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateRep)
                    .addComponent(btnBrand))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowCus)
                    .addComponent(btnShowRep)
                    .addComponent(btnChngActivity)
                    .addComponent(btnShowComp)
                    .addComponent(btnDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        AdminPage.this.setVisible(false);
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        UserFileLogger.logUserLogout(UserManager.getUser());
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCreateRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRepActionPerformed
        AdminPage.this.setVisible(false);
        AddRepresentativePage addRepPage = new AddRepresentativePage();
        addRepPage.setVisible(true);
    }//GEN-LAST:event_btnCreateRepActionPerformed

    private void btnShowCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCusActionPerformed
        listUserTable.clear();
        customerTable.setRowCount(0);
        jTable1.setModel(customerTable);
        customerTable.setColumnIdentifiers(new String[]{"Name", "Surname", "Email", "Active"});
        
        
        EntityManager em = null;
        try {
            em = PersistenceManager.getEntityManager();
            TypedQuery<Customer> query = em.createQuery("SELECT c FROM Customer c", Customer.class);
            List<Customer> customers = query.getResultList();

            for (Customer c : customers) {
                customerTable.addRow(new Object[]{
                    c.getFirstName(),
                    c.getLastName(),
                    c.getEmail(),
                    c.getActive()
                });
                listUserTable.add(c);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching customers: " + e.getMessage());
        } finally {
            if (em != null) em.close();
        }
    }//GEN-LAST:event_btnShowCusActionPerformed

    private void btnShowRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRepActionPerformed
        listUserTable.clear();
        repTable.setRowCount(0); 
        jTable1.setModel(repTable);
        repTable.setColumnIdentifiers(new String[]{"Name", "Surname", "Email", "Brand", "Active"});
        
        EntityManager em = null;
        try {
            em = PersistenceManager.getEntityManager();
            TypedQuery<CustomerRepresentative> query = em.createQuery("SELECT r FROM CustomerRepresentative r", CustomerRepresentative.class);
            List<CustomerRepresentative> reps = query.getResultList();

            for (CustomerRepresentative c : reps) {
                repTable.addRow(new Object[]{
                    c.getFirstName(),
                    c.getLastName(),
                    c.getEmail(),
                    (c.getAssignedBrand() != null ? c.getAssignedBrand().getName() : "-"),
                    c.getActive()
                });
                listUserTable.add(c);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching representatives: " + e.getMessage());
        } finally {
            if (em != null) em.close();
        }
    }//GEN-LAST:event_btnShowRepActionPerformed

    private void btnChngActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChngActivityActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            int state = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (state == JOptionPane.YES_OPTION) {
                User selectedUser = listUserTable.get(jTable1.getSelectedRow());

                EntityManager em = null;
                try {
                    em = PersistenceManager.getEntityManager();
                    em.getTransaction().begin();
                    User managedUser = em.find(User.class, selectedUser.getId());
                    managedUser.setActive(!managedUser.getActive());
                    em.getTransaction().commit();
                    UserFileLogger.logUserActivationChanged(managedUser, !managedUser.getActive());
                    JOptionPane.showMessageDialog(this, "User activity updated.");

                    // Refresh table
                    if (selectedUser instanceof Customer) {
                        btnShowCusActionPerformed(null);
                    } else if (selectedUser instanceof CustomerRepresentative) {
                        btnShowRepActionPerformed(null);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error updating activity: " + e.getMessage());
                    if (em != null && em.getTransaction().isActive()) {
                        em.getTransaction().rollback();
                    }
                } finally {
                    if (em != null) em.close();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a user.");
        }
    }//GEN-LAST:event_btnChngActivityActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        AdminPage.this.setVisible(false);
        EditPage editPage = new EditPage();
        editPage.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnShowCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCompActionPerformed
        complaintTable.setRowCount(0);
        jTable1.setModel(complaintTable);
        complaintTable.setColumnIdentifiers(new String[]{"Active", "Created On", "Customer", "Last Updated By", "Brand", "Subject", "Status"});
        
        EntityManager em = null;
        try {
            em = PersistenceManager.getEntityManager();
            TypedQuery<Complaint> query = em.createQuery("SELECT c FROM Complaint c", Complaint.class);
            listComplaintTable = query.getResultList();

            for (Complaint c : listComplaintTable) {
                String repEmail = (c.getRep() != null) ? c.getRep().getEmail() : "-";
                complaintTable.addRow(new Object[]{
                    c.getActive(),
                    c.getDate(),
                    c.getCustomer().getEmail(),
                    repEmail,
                    c.getBrand().getName(),
                    c.getSubject(),
                    c.getStatus()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching complaints: " + e.getMessage());
        } finally {
            if (em != null) em.close();
        }
    }//GEN-LAST:event_btnShowCompActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            CustomerRepresentative.selectedComplaint = listComplaintTable.get(jTable1.getSelectedRow());
            this.setVisible(false);
            ComplaintDetailsPage complaintDetailsPage = new ComplaintDetailsPage();
            complaintDetailsPage.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(AdminPage.this, "Please select a complaint.");
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        AdminPage.this.setVisible(false);
        BrandPage brandPage = new BrandPage();
        brandPage.setVisible(true);
    }//GEN-LAST:event_btnBrandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnChngActivity;
    private javax.swing.JButton btnCreateRep;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShowComp;
    private javax.swing.JButton btnShowCus;
    private javax.swing.JButton btnShowRep;
    private javax.swing.JButton btnViewComplaintLogs;
    private javax.swing.JButton btnViewUserLogs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables

}
