package project;

import java.util.List;
import javax.swing.JOptionPane;
import javax.persistence.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class CreateComplaintPage extends BaseFrame {

    /**
     * Creates new form CreateComplaintPage
     */
    public CreateComplaintPage() {
        super();
        initComponents();
        loadBrandsToComboBox();
        setupListeners();

    }

    private void loadBrandsToComboBox() {
        cmbBoxBrand.removeAllItems();

        EntityManager em = null;
        try {
            em = PersistenceManager.getEntityManager();
            TypedQuery<Brand> query = em.createQuery("SELECT b FROM Brand b WHERE b.active = true AND b.id > 1", Brand.class);
            List<Brand> brands = query.getResultList();

            for (Brand b : brands) {
                cmbBoxBrand.addItem(b);
            }
            if (!brands.isEmpty()) {
                cmbBoxBrand.setSelectedIndex(0);
                updateProductList((Brand) cmbBoxBrand.getSelectedItem());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading brands: " + e.getMessage());
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
        }
    }

    private void setupListeners() {
        cmbBoxBrand.addActionListener(evt -> {
            Brand selectedBrand = (Brand) cmbBoxBrand.getSelectedItem();
            if (selectedBrand != null) {
                updateProductList(selectedBrand);
            }
        });
    }

    private void updateProductList(Brand brand) {

        cmbProduct.removeAllItems();

        EntityManager em = null;
        try {
            em = PersistenceManager.getEntityManager();
            Brand managedBrand = em.find(Brand.class, brand.getId());
            if (managedBrand != null && managedBrand.getProducts() != null) {
                for (Product p : managedBrand.getProducts()) {
                    if (p.getActive()) {
                        cmbProduct.addItem(p);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading products: " + e.getMessage());
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBoxBrand = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbBoxSubject = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        btnCreateComplaint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbProduct = new javax.swing.JComboBox<>();

        jLabel1.setText("Brand");

        jLabel2.setText("Product Modal");

        jLabel3.setText("Subject");

        cmbBoxSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product Issues", "Customer Service", "Delivery & Shipping", "Order Issues", "Pricing & Refund" }));

        jLabel4.setText("Detail");

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        jScrollPane1.setViewportView(txtDetail);

        btnCreateComplaint.setText("Create Complaint");
        btnCreateComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateComplaintActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCreateComplaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(33, 33, 33))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(cmbBoxBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBoxSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateComplaint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        CreateComplaintPage.this.setVisible(false);
        CustomerPage customerPage = new CustomerPage();
        customerPage.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateComplaintActionPerformed
        EntityManager em = null;
        try {
            em = PersistenceManager.getEntityManager();
            em.getTransaction().begin();

            Customer currentCustomer = em.find(Customer.class, ((Customer) UserManager.getUser()).getId());

            Brand selectedBrand = (Brand) cmbBoxBrand.getSelectedItem();
            Product selectedProduct = (Product) cmbProduct.getSelectedItem();
            String subject = (String) cmbBoxSubject.getSelectedItem();
            String detail = txtDetail.getText().trim();

            if (txtDetail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(CreateComplaintPage.this, "Please fill in all fields.");
                return;
            }
            if (selectedProduct == null) {
                JOptionPane.showMessageDialog(CreateComplaintPage.this, "Selected product modal is not valid.");
                return;
            }

            if (selectedBrand == null) {
                JOptionPane.showMessageDialog(CreateComplaintPage.this, "Selected brand is not valid.");
                return;
            }

            TypedQuery<Long> countQuery = em.createQuery(
                    "SELECT COUNT(c) FROM Complaint c WHERE c.customer = :customer AND c.product = :product AND c.brand = :brand AND c.subject = :subject AND c.active = true",
                    Long.class);
            countQuery.setParameter("customer", currentCustomer);
            countQuery.setParameter("product", selectedProduct);
            countQuery.setParameter("brand", selectedBrand);
            countQuery.setParameter("subject", subject);
            Long existingCount = countQuery.getSingleResult();

            if (existingCount > 0) {
                JOptionPane.showMessageDialog(this, "You have already submitted an active complaint for this product and subject.");
                return;
            }

            // Create the complaint and add it to the system
            Complaint complaint = new Complaint(
                    currentCustomer,
                    selectedBrand,
                    selectedProduct,
                    subject,
                    txtDetail.getText(),
                    true);
            em.persist(complaint);
            em.getTransaction().commit();
            ComplaintFileLogger.logChange("[CREATE] New complaint created | "
                    + "Complaint ID: " + complaint.getId()
                    + " | Customer: " + complaint.getCustomer().getEmail()
                    + " | Product: " + complaint.getProduct().getName()
                    + " | Subject: " + complaint.getSubject()
                    + " | Brand: " + complaint.getBrand().getName()
                    + " | Status: " + complaint.getStatus()
                    + " | Created On: " + complaint.getDate());

            JOptionPane.showMessageDialog(CreateComplaintPage.this, "Complaint created successfully.");
            CreateComplaintPage.this.setVisible(false);
            CustomerPage customerPage = new CustomerPage();
            customerPage.setVisible(true);
        } catch (Exception e) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(CreateComplaintPage.this, "An error occurred: " + e.getMessage());
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
        }
    }//GEN-LAST:event_btnCreateComplaintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateComplaintPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateComplaintPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateComplaintPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateComplaintPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CreateComplaintPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateComplaint;
    private javax.swing.JComboBox<Brand> cmbBoxBrand;
    private javax.swing.JComboBox<String> cmbBoxSubject;
    private javax.swing.JComboBox<Product> cmbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDetail;
    // End of variables declaration//GEN-END:variables
}
