package project;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author LENOVO
 */
public class RepresentativePage extends BaseFrame {

    public DefaultTableModel complaintTable = new DefaultTableModel();
    List<Complaint> listTable = new ArrayList<>();

    /**
     * Creates new form RepresentativePage
     */
    public RepresentativePage() {
        super();
        initComponents();

        CustomerRepresentative currentUser = (CustomerRepresentative) UserManager.getUser();
        lblUserName.setText(currentUser.getFirstName() + " " + currentUser.getLastName());
        lblRepBrand.setText(currentUser.getAssignedBrand().getName());

        // JTable modelini ayarla
        jTable1.setModel(complaintTable);
        complaintTable.setColumnIdentifiers(new String[]{"Complaint Id", "Created On", "Customer", "Product Modal", "Subject", "Status"});

        // Başlangıçta tüm şikayetleri yükle
        loadComplaints("All");

    }

    private void loadComplaints(String statusFilter) {

        CustomerRepresentative currentUser = (CustomerRepresentative) UserManager.getUser();
        int brandId = currentUser.getAssignedBrand().getId();

        complaintTable.setRowCount(0);

        String sql = "SELECT c.id, c.complaint_date, cu.email, p.name, c.subject, c.status "
                + "FROM complaints c "
                + "JOIN users cu ON c.customer_id = cu.id "
                + "JOIN products p ON c.product_id = p.id "
                + "WHERE c.brand_id = ? AND c.active = true";

        if (!statusFilter.equals("All")) {
            sql += " AND c.status = ?";
        }

        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, brandId);
            if (!statusFilter.equals("All")) {
                stmt.setString(2, statusFilter);
            }

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {

                    complaintTable.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getDate("complaint_date"),
                        rs.getString("email"),
                        rs.getString("name"),
                        rs.getString("subject"),
                        rs.getString("status")
                    });

                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading complaints: " + e.getMessage());
        }

    }

    private Complaint getComplaintById(int id) {
        String sql = "SELECT c.*, cu.email AS customer_email, p.name AS product_name "
                + "FROM complaints c "
                + "JOIN users cu ON c.customer_id = cu.id "
                + "JOIN products p ON c.product_id = p.id "
                + "WHERE c.id = ?";

        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, id);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Customer customer = new Customer();
                    customer.setId(rs.getInt("customer_id"));
                    customer.setEmail(rs.getString("customer_email"));
                    // customer için diğer alanlar set edilebilir

                    Product product = new Product();
                    product.setId(rs.getInt("product_id"));
                    product.setName(rs.getString("product_name"));
                    // product için diğer alanlar set edilebilir

                    Brand brand = new Brand();
                    brand.setId(rs.getInt("brand_id"));
                    // brand için diğer alanlar set edilebilir

                    Complaint complaint = new Complaint(
                            customer,
                            brand,
                            product,
                            rs.getString("subject"),
                            rs.getString("detail"),
                            rs.getBoolean("active")
                    );
                    complaint.setId(rs.getInt("id"));
                    complaint.setDate(rs.getDate("complaint_date").toLocalDate());
                    complaint.setStatus(rs.getString("status"));

                    return complaint;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnChangeStatus = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblUserName = new javax.swing.JLabel();
        lblRepBrand = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Id", "Subject", "Statu"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnChangeStatus.setText("Change Status");
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Created", "In Progress", "Dispute" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblUserName.setText("jLabel1");

        lblRepBrand.setText("jLabel1");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblUserName)
                                .addGap(44, 44, 44)
                                .addComponent(lblRepBrand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit)
                                .addGap(28, 28, 28)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangeStatus)))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(lblRepBrand)
                    .addComponent(lblUserName)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        RepresentativePage.this.setVisible(false);
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        UserFileLogger.logUserLogout(UserManager.getUser());
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int complaintId = (int) complaintTable.getValueAt(selectedRow, 0); // ID sütunu indexi 0
            Complaint selectedComplaint = getComplaintById(complaintId);
            if (selectedComplaint != null) {
                CustomerRepresentative.selectedComplaint = selectedComplaint;
                this.setVisible(false);
                new ChangeStatusPage().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Complaint could not be found.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a complaint.");
        }

    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Filter complaints by selected status from the combo box
        listTable.clear();
        complaintTable.setRowCount(0);
        String selectedStatus = jComboBox1.getSelectedItem().toString();
        loadComplaints(selectedStatus);


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        RepresentativePage.this.setVisible(false);
        EditPage editPage = new EditPage();
        editPage.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RepresentativePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblRepBrand;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables

}
