
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class ComplaintDetailsPage extends javax.swing.JFrame {
    DefaultListModel<String> messagesModel = new DefaultListModel<>();

    /**
     * Creates new form ComplaintDetailsPage
     */
    public ComplaintDetailsPage() {
        initComponents();
        messagesModel.clear();
        if (CustomerRepresentative.selectedComplaint.getSolutions() != null) {
            for (String solution : CustomerRepresentative.selectedComplaint.getSolutions()) {
                messagesModel.addElement(solution);
            }
        }
        lblStatu.setText(CustomerRepresentative.selectedComplaint.getStatus());
        lblBrand.setText(CustomerRepresentative.selectedComplaint.getBrand());
        lblProductId.setText(CustomerRepresentative.selectedComplaint.getProductId());
        lblSubject.setText(CustomerRepresentative.selectedComplaint.getSubject());
        lblDetail.setText(CustomerRepresentative.selectedComplaint.getDetail());
        lstMessages.setModel(messagesModel);
        
        if (!(UserManager.getUser() instanceof Customer)) {
        btnObjection.setVisible(false);
        btnEdit.setVisible(false);
        btnDelete.setVisible(false);
        }
        if(CustomerRepresentative.selectedComplaint.getObjection() != null && !CustomerRepresentative.selectedComplaint.getObjection().isEmpty()){
            jLabel7.setVisible(true);
            lblObjection.setVisible(true);
            lblObjection.setText(CustomerRepresentative.selectedComplaint.getObjection());           
        }else{
            jLabel7.setVisible(false);
            lblObjection.setVisible(false);
            btnDelete.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStatu = new javax.swing.JLabel();
        lblProductId = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnObjection = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblObjection = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMessages = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Detail          :");

        jLabel1.setText("Brand          :");

        jLabel5.setText("Messages    :");

        lblStatu.setText("jLabel5");

        lblProductId.setText("jLabel5");

        lblSubject.setText("jLabel5");

        lblDetail.setText("jLabel5");

        jLabel2.setText("Product Id   :");

        jLabel3.setText("Subject        :");

        jLabel6.setText("Statu           :");

        lblBrand.setText("jLabel7");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnObjection.setText("Objection");
        btnObjection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjectionActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel7.setText("Objection    :");

        lblObjection.setText("jLabel8");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lstMessages.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstMessages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObjection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatu)
                    .addComponent(lblProductId)
                    .addComponent(lblSubject)
                    .addComponent(lblDetail)
                    .addComponent(lblBrand)
                    .addComponent(lblObjection)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblStatu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblProductId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSubject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDetail))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblObjection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnObjection)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ComplaintDetailsPage.this.setVisible(false);
        if (UserManager.getUser() instanceof Customer){
            CustomerPage customerPage = new CustomerPage();
            customerPage.setVisible(true);
        }
        if (UserManager.getUser() instanceof Admin){
            AdminPage adminPage = new AdminPage();
            adminPage.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnObjectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjectionActionPerformed
        if (CustomerRepresentative.selectedComplaint.getStatus().equals("Resolved")) {
            String objectionMessage = JOptionPane.showInputDialog("Please enter the reason for your objection:");
            // Check if input was not canceled or left empty
            if (objectionMessage != null && !objectionMessage.trim().isEmpty()) {
                JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Your objection has been received: " + objectionMessage);
                CustomerRepresentative.selectedComplaint.setStatus("Dispute");
                CustomerRepresentative.selectedComplaint.setActive(true);
                CustomerRepresentative.selectedComplaint.setObjection(objectionMessage);
                jLabel7.setVisible(true);
                lblObjection.setVisible(true);
                lblObjection.setText(objectionMessage);
                lblStatu.setText(CustomerRepresentative.selectedComplaint.getStatus());
            } else {
                JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Objection input was canceled or left empty.");
            }
        } else {
            JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Objections are not allowed for complaints in this status!");
        }
    }//GEN-LAST:event_btnObjectionActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (CustomerRepresentative.selectedComplaint.getActive()) {
            if (!"Dispute".equals(CustomerRepresentative.selectedComplaint.getStatus())) {
                String updateDetail = JOptionPane.showInputDialog("Please enter the updated complaint detail:", CustomerRepresentative.selectedComplaint.getDetail());
                // Check if input was not canceled or left empty
                if (updateDetail != null && !updateDetail.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Complaint detail has been updated: " + updateDetail);
                    CustomerRepresentative.selectedComplaint.setDetail(updateDetail);
                    lblDetail.setText(updateDetail);
                } else {
                    JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Detail input was canceled or left empty.");
                }
            } else {
                String updateDispute = JOptionPane.showInputDialog("Please enter the updated complaint objection reason:", CustomerRepresentative.selectedComplaint.getDetail());
                // Check if input was not canceled or left empty
                if (updateDispute != null && !updateDispute.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Complaint objection reason has been updated: " + updateDispute);
                    CustomerRepresentative.selectedComplaint.setObjection(updateDispute);
                    lblObjection.setText(updateDispute);
                } else {
                    JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Reason input was canceled or left empty.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "You can edit only active complaint.");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (CustomerRepresentative.selectedComplaint.getActive()) {
            CustomerRepresentative.selectedComplaint.setActive(false);
            CustomerRepresentative.selectedComplaint.setStatus("Deleted");
            JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "Complaint succesfully deleted.");
        } else {
            JOptionPane.showMessageDialog(ComplaintDetailsPage.this, "You can delete only active complaint!!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplaintDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplaintDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplaintDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplaintDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplaintDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnObjection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblObjection;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblStatu;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JList<String> lstMessages;
    // End of variables declaration//GEN-END:variables
}
